# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Steve's Github Blog
email: stephen.fell@gmail.com   
description: > # this means to ignore newlines until "baseurl:"
  Github page for Stephen Fell: a mechanical engineer and experienced data analyst who likes using Python to solve problems.  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://engrinak.github.io" # the base hostname & protocol for your site
twitter_username: 
linkedin_profile: https://www.linkedin.com/in/stephen-fell/
github_username:  engrinak

# Build settings
markdown: kramdown

permalink: /:categories/:title/

theme: minima
minima:
  skin: dark
